name: autofix.ci

on:
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.12.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

  handle-new-assets:
    needs: [setup]
    name: Handle new assets
    runs-on: ubuntu-latest

    steps:
      - name: Convert new assets to svg
        if: ${{ !cancelled() }}
        run: pnpm convert-new-assets-to-svg

      - name: Clean assets
        if: ${{ !cancelled() }}
        run: pnpm clean-assets

  lint:
    needs: [setup]
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Prettier
        if: ${{ !cancelled() }}
        run: pnpm format

      - name: Type check
        if: ${{ !cancelled() }}
        run: pnpm type-check

  commit-changes:
    name: Commit changes with autofix.ci
    runs-on: ubuntu-latest
    needs: [setup, handle-new-assets, lint]

    steps:
      - name: Commit clean assets
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
