name: Validate protocols, tokens, validators, and vaults

on:
  pull_request:
    paths:
      - .github/workflows/validate.yml
      - src/vaults/**/*.json
      - src/tokens/**/*.json
      - src/validator/**/*.json
      - src/schema/*.json
      - scripts/**/*.*
      - package.json

env: 
    QUICKNODE_TOKEN: ${{ secrets.QUICKNODE_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Validate protocols, tokens, validators, and vaults
        run: pnpm validate

      - name: Commit clean data
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
